version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: miv_postgres
    environment:
      POSTGRES_USER: app_miv
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: app_miv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_miv"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
